public with sharing class ApiResponsePropertyWrapper {
    public String id { get; set; }
    public String company_id { get; set; }
    public String name { get; set; }
    public String address_1 { get; set; }
    public String address_2 { get; set; }
    public String city { get; set; }
    public String state { get; set; }
    public String zip { get; set; }
    public String country { get; set; }
    public Boolean active { get; set; }
}