public class ApiResponseSectionWrapper {
    public String id { get; set; }
    public String company_id { get; set; }
    public String property_id { get; set; }
    public String code { get; set; }
    public String Name { get; set; }
    public String total_area { get; set; }
    public String asset_type { get; set; }
    public String classification_name { get; set; }
    public Datetime deleted_at { get; set; }
}