public class ApiResponseDefectWrapper {
    public String id { get; set; }
    public String company_id { get; set; }
    public String property_id { get; set; }
    public String section_id { get; set; }
    public String survey_id { get; set; }
    public String asset_type { get; set; }
    public String asset_material_type { get; set; }
    public String building_name { get; set; }
    public String section_code { get; set; }
    public String name { get; set; }
    public String label { get; set; }
    public String uom { get; set; }
    public String severity_title { get; set; }
    public String DefTitle { get; set; }
    public String WBSDefID { get; set; }
    public Integer quantity { get; set; }
    public String status { get; set; }
    public String recommendation { get; set; }
    public Datetime deleted_at { get; set; }
    
}