public class MantisContact {
    	//public String Name {get; set;}
        public Integer CompanyID {get; set;}
        //public Integer BuildingID {get; set;}
        //public String BuildingGUID {get; set;}
        //public String BuildingName {get; set;}
        //public String ContactType {get; set;}
        public String FirstName {get; set;}
        public String LastName {get; set;}
        public String Phone1 {get; set;}
        public String Email {get; set;}
}